### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by cronos45** [eduherminio/Nunchuck#5]
Hello, I have been trying to use your code with arduino uno and a adafruit motor shield V2 to no avail. Any chance you could help me under stand how to control the motors only so I can add it to my working servo code?

**Comment by eduherminio** [comment]
Hi @cronos45,
Just to make sure, you want to control a DC motor (using that motor shield) extracting data from a Nunchuck?

**Comment by cronos45** [comment]
Yes, I have it so I can control the servos with the joystick but can not get beyond that. `#include <Wire.h>
#include <Adafruit_MotorShield.h>
#include "utility/Adafruit_MS_PWMServoDriver.h"
 
// Create the motor shield object with the default I2C address
Adafruit_MotorShield AFMS = Adafruit_MotorShield(); 
// Or, create it with a different I2C address (say for stacking)
// Adafruit_MotorShield AFMS = Adafruit_MotorShield(0x61); 
 
// Set up the left motor on port M4
Adafruit_DCMotor *leftMotor = AFMS.getMotor(1);
// Set up the right motor on port M3
Adafruit_DCMotor *rightMotor = AFMS.getMotor(2);
 
void setup() {
  Serial.begin(9600);           // set up Serial library at 9600 bps
  Serial.println("Adafruit Motorshield v2 - Robot Test!");
 
  AFMS.begin();  // create with the default frequency 1.6KHz
  //AFMS.begin(1000);  // OR with a different frequency, say 1KHz
}
 
void loop() {
  // Set the speed to start, from 0 (off) to 255 (max speed)
  leftMotor->setSpeed(100);
  rightMotor->setSpeed(100);
  
  leftMotor->run(FORWARD); //LEFT MOTOR FULL STEAM AHEAD!
  rightMotor->run(FORWARD); //RIGHT MOTOR FULL STEAM AHEAD!
}'

**Comment by eduherminio** [comment]
I assume you already have the Nunchuck-Arduino adapter.
I'll try to provide a refactored, English example in the following days that you can fully understand.

**Comment by cronos45** [comment]
Wait! It must be wireless?

`#include <Wire.h>
#include <Servo.h>
#include <Adafruit_MotorShield.h>
#include "utility/Adafruit_MS_PWMServoDriver.h"

// check the pin before connecting to the motor shield
#define led_pin                     13  
#define music_pin                   6
 
#define ForwardSpeed                255
#define ReverseSpeed                200
#define TurningSpeed                145

#define pwrpin PORTC3
#define gndpin PORTC2

// Create the motor shield object with the default I2C address
Adafruit_MotorShield AFMS = Adafruit_MotorShield(); 
 
// Set up the left motor on port M4
Adafruit_DCMotor *leftMotor = AFMS.getMotor(1);
// Set up the right motor on port M3
Adafruit_DCMotor *rightMotor = AFMS.getMotor(2);

Servo servoLeft;          // Define left servo
Servo servoRight;         // Define right servo

static uint8_t nunchuck_buf[6];   // array to store nunchuck data,

void z_button_handle(){
  /*
   * this function will called repeatedly 
   * when z buttion is pressed
  */
  digitalWrite(led_pin, HIGH);
  Serial.println("Z-button is pressed");
}

void c_button_handle(){
  /*
   * this function will called repeatedly 
   * when c buttion is pressed
  */
  tone(music_pin, 1000); /* Generate tone of 1kHz on tone pin*/
  Serial.println("C-button is pressed");
}

void motor_control(int x, int y){
  /*
   * function to control the direction of dc motor
   * depending on the angle of servo motor
   * whic in turn depend on accelerometer
   * 
   * x: control the left motor
   * y: control the right motor
   * 
   * if angle of servo is greater than 92  the motor will move forward
   * if angle of servo is less than 88 the motor will move backwar
   * in between 92 and 88 the motor should remain off
  */
  if(x > 92){
    leftMotor->setSpeed(ForwardSpeed);
    leftMotor->run(FORWARD);
  }else if(x < 88){
    leftMotor->setSpeed(ReverseSpeed);
    leftMotor->run(BACKWARD);
  }else{
    leftMotor->run(RELEASE);
  }

  
  if(y > 92){
    rightMotor->setSpeed(ForwardSpeed);
    rightMotor->run(FORWARD);
  }else if(y < 88){
    rightMotor->setSpeed(ReverseSpeed);
    rightMotor->run(BACKWARD);
  }else{
    rightMotor->run(RELEASE);
  }
}

void setup()
{
  Serial.begin(19200);
  
  servoLeft.attach(10);  // Set left servo to digital pin 10
  servoRight.attach(9);  // Set right servo to digital pin 9
  
  nunchuck_setpowerpins(); // use analog pins 2&3 as fake gnd & pwr
  nunchuck_init(); // send the initilization handshake

  AFMS.begin();
  // turn off both motor initially
  leftMotor->run(RELEASE);
  rightMotor->run(RELEASE);

  // make led pin output
  pinMode(led_pin, OUTPUT);
  
  Serial.print ("Finished setup\n");
}

void loop()
{
  nunchuck_get_data();

// map nunchuk data to a servo data point
  int x_axis = map(nunchuck_buf[0], 23, 222, 180, 0);
  int y_axis = map(nunchuck_buf[1], 32, 231, 0, 180);

// move servo to desired position based on Wii nunchuk reading
  servoLeft.write(x_axis);
  servoRight.write(y_axis);
  
// DC motor control
   motor_control(x_axis, y_axis);
   
// Button functionality
  if ((nunchuck_buf[5] >> 0) & 1){
    // z button is pressed
     z_button_handle();
  }else{
    digitalWrite(led_pin, LOW);
  }
    
  if ((nunchuck_buf[5] >> 1) & 1){
    // c button is pressed
    c_button_handle();
  }else{
    noTone(music_pin);
  }
    
// un-comment next line to print data to serial monitor  
//  nunchuck_print_data();          
}


//
// Nunchuck functions
//

// Uses port C (analog in) pins as power & ground for Nunchuck
static void nunchuck_setpowerpins()
{
    DDRC |= _BV(pwrpin) | _BV(gndpin);
    PORTC &=~ _BV(gndpin);
    PORTC |=  _BV(pwrpin);
    delay(100);  // wait for things to stabilize        
}

// initialize the I2C system, join the I2C bus,
// and tell the nunchuck we're talking to it
void nunchuck_init()
{ 
  Wire.begin();                      // join i2c bus as master
  Wire.beginTransmission(0x52);     // transmit to device 0x52
  Wire.write(0x40);            // sends memory address
  Wire.write(0x00);            // sends sent a zero.  
  Wire.endTransmission();     // stop transmitting
}

// Send a request for data to the nunchuck
// was "send_zero()"
void nunchuck_send_request()
{
  Wire.beginTransmission(0x52);     // transmit to device 0x52
  Wire.write(0x00);            // sends one byte
  Wire.endTransmission();     // stop transmitting
}

// Receive data back from the nunchuck, 
int nunchuck_get_data()
{
    int cnt=0;
    Wire.requestFrom (0x52, 6);     // request data from nunchuck
    while (Wire.available ()) {
      // receive byte as an integer
      nunchuck_buf[cnt] = nunchuk_decode_byte(Wire.read());
      cnt++;
    }
    nunchuck_send_request();  // send request for next data payload
    // If we recieved the 6 bytes, then go print them
    if (cnt >= 5) {
     return 1;   // success
    }
    return 0; //failure
}

// Print the input data we have recieved
// accel data is 10 bits long
// so we read 8 bits, then we have to add
// on the last 2 bits.  That is why I
// multiply them by 2 * 2
void nunchuck_print_data()
{ 
  static int i=0;
  int joy_x_axis = nunchuck_buf[0];
  int joy_y_axis = nunchuck_buf[1];

  int accel_x_axis = nunchuck_buf[2]; // * 2 * 2; 
  int accel_y_axis = nunchuck_buf[3]; // * 2 * 2;
  int accel_z_axis = nunchuck_buf[4]; // * 2 * 2;


  int z_button = 0;
  int c_button = 0;

  // byte nunchuck_buf[5] contains bits for z and c buttons
  // it also contains the least significant bits for the accelerometer data
  // so we have to check each bit of byte outbuf[5]
  if ((nunchuck_buf[5] >> 0) & 1) 
    z_button = 1;
  if ((nunchuck_buf[5] >> 1) & 1)
    c_button = 1;

  if ((nunchuck_buf[5] >> 2) & 1) 
    accel_x_axis += 2;
  if ((nunchuck_buf[5] >> 3) & 1)
    accel_x_axis += 1;

  if ((nunchuck_buf[5] >> 4) & 1)
    accel_y_axis += 2;
  if ((nunchuck_buf[5] >> 5) & 1)
    accel_y_axis += 1;

  if ((nunchuck_buf[5] >> 6) & 1)
    accel_z_axis += 2;
  if ((nunchuck_buf[5] >> 7) & 1)
    accel_z_axis += 1;

  Serial.print(i,DEC);
  Serial.print("\t");
  
  Serial.print("joy:");
  Serial.print(joy_x_axis,DEC);
  Serial.print(",");
  Serial.print(joy_y_axis, DEC);
  Serial.print("  \t");

  Serial.print("acc:");
  Serial.print(accel_x_axis, DEC);
  Serial.print(",");
  Serial.print(accel_y_axis, DEC);
  Serial.print(",");
  Serial.print(accel_z_axis, DEC);
  Serial.print("\t");

  Serial.print("but:");
  Serial.print(z_button, DEC);
  Serial.print(",");
  Serial.print(c_button, DEC);

  Serial.print("\r\n");  // newline
  i++;
}

// Encode data to format that most wiimote drivers except
// only needed if you use one of the regular wiimote drivers
char nunchuk_decode_byte (char x)
{
  x = (x ^ 0x17) + 0x17;
  return x;
}
'  I almost figured it out, but now the motors relay on the joystick moving so angle of servo determines motor position(not ideal or easy)

**Comment by cronos45** [comment]
My spanish brain overlooked servo motor part. Does this mean I am attempting a useless effort? ie the more can not be controlled via accel?

**Comment by eduherminio** [comment]
I'm curious about your hardware, is controlling both DC motors with another two servomotors a requirement?
I've managed to control quite precisely a simple, two wheels robot with just adjusting each motor speed; and in case of having them joined by an axis, I would use just a servomotor to control direction.

**Comment by cronos45** [comment]
This kit https://learn.adafruit.com/adabox002/assembling-your-robot   And adafruit motor shield V2 and arduino uno. plus two servos and wii nunchuck wired(ordered wireless)

**Comment by eduherminio** [comment]
As I said, easiest way of controlling DC motors is just passing them different values and forgetting about using a servomotor for that. [Here you have an example using a 1€ IR remote control kit](https://github.com/eduherminio/motorIR).
In this specific case, I'd just use two accelerometers: one for speed (0 max backwards, 180 max forwards, 90 stopped) and another one for direction (extracting a decimal coeff between 0 and 1 from Nunchuck accel and multiplying each motor speed for coeff and (1-coeff), avoiding once again using servos for that).
Do you get my idea?
